//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityThoughts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class botToken {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal botToken() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunityThoughts.botToken", typeof(botToken).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1290465865507450885-lcUWWB5gVDn5JtnvKEM8j1Lq9zeUnY.
        /// </summary>
        internal static string accessToken {
            get {
                return ResourceManager.GetString("accessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C7WNnYoJ16aZERSK1JWBJgPcwsIwSQSNeR4NfUbgSouTw.
        /// </summary>
        internal static string accessTokenSecret {
            get {
                return ResourceManager.GetString("accessTokenSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NzM5NTQ1NTcwNTM5OTk1MzE2.GY3JeA.qPcUOUEqF9qgXQV72Dk8oIHUtgScXt5JNbUv90.
        /// </summary>
        internal static string clientToken {
            get {
                return ResourceManager.GetString("clientToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKBRqhTJ5RPudxVux0RYvQHzR.
        /// </summary>
        internal static string consumerKey {
            get {
                return ResourceManager.GetString("consumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rCQil6S1Yn4umvDADow1cRe1M7lSCxngLJn58ppL0g4NQhUapl.
        /// </summary>
        internal static string consumerSecret {
            get {
                return ResourceManager.GetString("consumerSecret", resourceCulture);
            }
        }
    }
}
